version: "3.1"
services:
    app:
        user: node
        container_name: wgu-capstone
        build:
            context: ./../
            args:
                - UNAME=${AT_USER}
                - UID=${AT_UID}
                - GID=${AT_GID}
            dockerfile: docker/${DOCKERFILE}
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - /home/node/app/node_modules
            - /home/node/app/.next
            - ./../:/home/node/app
